#!/usr/bin/env bash

if [[ "$#" -ne 2 ]]; then
    echo "Must give terminal name followed by either 'vim', 'nvim', or 'gvim' as cli arguments."
    exit 1
fi

terminal=$1
vim=$2

function setclip {
    xclip -selection c
}

function getclip {
    xclip -selection clipboard -o
}

file=$(mktemp)
if [[ $vim == 'gvim' ]]; then
    $vim "$file"
else
    $terminal -e $vim "$file"
fi

cat $file | setclip
rm $file

xdotool key ctrl+shift+v
